//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNextHotel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Ratings = new HashSet<Rating>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int HotelID { get; set; }
        public int CityID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<bool> HasPool { get; set; }
        public Nullable<bool> HasParking { get; set; }
        public Nullable<bool> HasGym { get; set; }
        public Nullable<bool> HasSpaCenter { get; set; }
        public Nullable<bool> IsPetFriendly { get; set; }
        public Nullable<bool> HasWiFi { get; set; }
        public Nullable<bool> HasRestourant { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string Description { get; set; }
        public byte[] PhotoData { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
