//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNextHotel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomsID { get; set; }
        public int RoomTypesID { get; set; }
        public int HotelID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public byte[] PhotoData { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<bool> HasAirCondition { get; set; }
        public Nullable<bool> HasTV { get; set; }
        public Nullable<bool> HasBalcony { get; set; }
        public Nullable<bool> HasKitchen { get; set; }
        public Nullable<bool> HasPrivateBathroom { get; set; }
        public Nullable<decimal> Quadrature { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
